// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QUANLYBANHANG.Models;

#nullable disable

namespace QUANLYBANHANG.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationsMenuFormRelations", b =>
                {
                    b.Property<decimal>("IdMenuForm")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_MENU_FORM");

                    b.Property<decimal>("IdApplication")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_APPLICATION");

                    b.HasKey("IdMenuForm", "IdApplication");

                    b.HasIndex("IdApplication");

                    b.ToTable("APPLICATIONS_MENU_FORM_RELATIONS", (string)null);
                });

            modelBuilder.Entity("GroupRelationshipMenuForm", b =>
                {
                    b.Property<decimal>("PartyId")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("PARTY_ID");

                    b.Property<decimal>("IdGroup")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_GROUP");

                    b.Property<decimal>("IdMenuForm")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_MENU_FORM");

                    b.HasKey("PartyId", "IdGroup", "IdMenuForm");

                    b.HasIndex("IdMenuForm");

                    b.ToTable("GROUP_RELATIONSHIP_MENU_FORM", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.Applications", b =>
                {
                    b.Property<decimal>("IdApplication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_APPLICATION");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdApplication"));

                    b.Property<string>("ApplicationName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("APPLICATION_NAME");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.HasKey("IdApplication");

                    b.ToTable("APPLICATIONS", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.Gender", b =>
                {
                    b.Property<decimal>("PartyId")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("PARTY_ID");

                    b.Property<decimal>("GenderTypeId")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("GENDER_TYPE_ID");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime")
                        .HasColumnName("FROM_DATE");

                    b.Property<DateTime?>("ThruDate")
                        .HasColumnType("datetime")
                        .HasColumnName("THRU_DATE");

                    b.HasKey("PartyId", "GenderTypeId", "FromDate")
                        .HasName("PK__GENDER__3F865F66");

                    b.HasIndex("GenderTypeId");

                    b.ToTable("GENDER", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.GenderType", b =>
                {
                    b.Property<decimal>("GenderTypeId")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("GENDER_TYPE_ID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("GenderTypeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("GENDER_TYPE_NAME");

                    b.HasKey("GenderTypeId")
                        .HasName("PK__GENDER_TYPE__3D9E16F4");

                    b.ToTable("GENDER_TYPE", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.GroupUser", b =>
                {
                    b.Property<decimal>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_GROUP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdGroup"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("GroupName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("GROUP_NAME");

                    b.HasKey("IdGroup");

                    b.ToTable("GROUP_USER", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.GroupUserRelationshipUser", b =>
                {
                    b.Property<decimal>("PartyId")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("PARTY_ID");

                    b.Property<decimal>("IdGroup")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_GROUP");

                    b.HasKey("PartyId", "IdGroup")
                        .HasName("PK_GROUP_USER_RELATIONSHIP_USER_1");

                    b.HasIndex("IdGroup");

                    b.ToTable("GROUP_USER_RELATIONSHIP_USER", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.MenuForm", b =>
                {
                    b.Property<decimal>("IdMenuForm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_MENU_FORM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("IdMenuForm"));

                    b.Property<bool?>("DanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("DANH_MUC");

                    b.Property<decimal?>("IdMenuFormParent")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("ID_MENU_FORM_PARENT");

                    b.Property<string>("MenuFormName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("MENU_FORM_NAME");

                    b.Property<string>("MenuFormUrl")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MENU_FORM_URL");

                    b.Property<string>("Mota")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MOTA");

                    b.Property<byte?>("Sort")
                        .HasColumnType("tinyint")
                        .HasColumnName("SORT");

                    b.Property<byte?>("SortParent")
                        .HasColumnType("tinyint")
                        .HasColumnName("SORT_PARENT");

                    b.Property<bool?>("Visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("VISIBLE");

                    b.HasKey("IdMenuForm");

                    b.HasIndex("IdMenuFormParent");

                    b.ToTable("MENU_FORM", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.Party", b =>
                {
                    b.Property<decimal>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("PARTY_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("PartyId"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DEPARTMENT_ID");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("PasswordH")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("PASSWORD_H");

                    b.Property<string>("TypeOfParty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TYPE_OF_PARTY");

                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("USERNAME");

                    b.Property<string>("UsernameH")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("USERNAME_H");

                    b.HasKey("PartyId")
                        .HasName("PK_PARTY_1");

                    b.ToTable("PARTY", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.Person", b =>
                {
                    b.Property<decimal>("PartyId")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("PARTY_ID");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("CurrentEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CURRENT_EMAIL");

                    b.Property<string>("CurrentFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CURRENT_FIRST_NAME");

                    b.Property<decimal?>("CurrentGenderTypeId")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("CURRENT_GENDER_TYPE_ID");

                    b.Property<string>("CurrentLastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CURRENT_LAST_NAME");

                    b.Property<string>("CurrentMiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CURRENT_MIDDLE_NAME");

                    b.Property<string>("CurrentNickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CURRENT_NICKNAME");

                    b.Property<string>("CurrentPhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CURRENT_PHONE_NUMBER");

                    b.Property<DateTime?>("PeopleIdIssueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("PEOPLE_ID_ISSUE_DATE");

                    b.Property<string>("PeopleIdIssuePlace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEOPLE_ID_ISSUE_PLACE");

                    b.Property<string>("PeopleIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PEOPLE_ID_NUMBER");

                    b.Property<string>("PersonImage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PERSON_IMAGE");

                    b.HasKey("PartyId");

                    b.ToTable("PERSON", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbChitietgiohang", b =>
                {
                    b.Property<int>("Magiohang")
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANG");

                    b.Property<int>("Masanpham")
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAM");

                    b.Property<decimal>("Dongia")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("DONGIA");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<decimal?>("Thanhtien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasColumnName("THANHTIEN")
                        .HasComputedColumnSql("([SOLUONG]*[DONGIA])", true);

                    b.HasKey("Magiohang", "Masanpham");

                    b.HasIndex("Masanpham");

                    b.ToTable("tbCHITIETGIOHANG", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbChitiethoadon", b =>
                {
                    b.Property<int>("Machitiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACHITIET");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Machitiet"));

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("DONGIA");

                    b.Property<int?>("Mahoadon")
                        .HasColumnType("int")
                        .HasColumnName("MAHOADON");

                    b.Property<int?>("Masanpham")
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAM");

                    b.Property<decimal?>("Soluong")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("SOLUONG");

                    b.HasKey("Machitiet");

                    b.HasIndex("Mahoadon");

                    b.HasIndex("Masanpham");

                    b.ToTable("tbCHITIETHOADON", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbDanhmuc", b =>
                {
                    b.Property<int>("Madanhmuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADANHMUC");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madanhmuc"));

                    b.Property<int?>("Danhmuccha")
                        .HasColumnType("int")
                        .HasColumnName("DANHMUCCHA");

                    b.Property<string>("Mota")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MOTA");

                    b.Property<string>("Tendanhmuc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TENDANHMUC");

                    b.HasKey("Madanhmuc")
                        .HasName("PK__tbDANHMU__804E2884FBEE3276");

                    b.ToTable("tbDANHMUC", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbGiohang", b =>
                {
                    b.Property<int>("Magiohang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAGIOHANG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Magiohang"));

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<DateTime?>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTAO")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("CHUA_THANH_TOAN")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Magiohang")
                        .HasName("PK__tbGIOHAN__559F5534E34A6024");

                    b.ToTable("tbGIOHANG", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbHoadon", b =>
                {
                    b.Property<int>("Mahoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAHOADON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mahoadon"));

                    b.Property<int?>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<DateTime?>("Ngay")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAY");

                    b.Property<DateTime?>("Ngayduyet")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYDUYET");

                    b.Property<string>("Nguoiduyet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NGUOIDUYET");

                    b.Property<decimal?>("Tongtien")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("TONGTIEN");

                    b.Property<string>("Trangthai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("DA_DAT_HANG")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mahoadon");

                    b.HasIndex("Makhachhang");

                    b.ToTable("tbHOADON", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbKhanhhang", b =>
                {
                    b.Property<int>("Makhachhang")
                        .HasColumnType("int")
                        .HasColumnName("MAKHACHHANG");

                    b.Property<string>("Diachi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .HasColumnName("EMAIL")
                        .IsFixedLength();

                    b.Property<string>("Gioitinh")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("GIOITINH");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HOTEN");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MATKHAU");

                    b.Property<DateOnly?>("Ngaysinh")
                        .HasColumnType("date")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Taikhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TAIKHOAN");

                    b.HasKey("Makhachhang");

                    b.ToTable("tbKHANHHANG", (string)null);
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbSanpham", b =>
                {
                    b.Property<int>("Masanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MASANPHAM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masanpham"));

                    b.Property<decimal?>("Dongia")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("DONGIA");

                    b.Property<string>("Hinhanh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HINHANH");

                    b.Property<int?>("Madanhmuc")
                        .HasColumnType("int")
                        .HasColumnName("MADANHMUC");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<decimal?>("Soluong")
                        .HasColumnType("numeric(18, 0)")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Tensanpham")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TENSANPHAM");

                    b.HasKey("Masanpham")
                        .HasName("PK__tbSANPHA__9534C892800073C7");

                    b.HasIndex("Madanhmuc");

                    b.ToTable("tbSANPHAM", (string)null);
                });

            modelBuilder.Entity("ApplicationsMenuFormRelations", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.Applications", null)
                        .WithMany()
                        .HasForeignKey("IdApplication")
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATIONS_MENU_FORM_RELATIONS_APPLICATIONS");

                    b.HasOne("QUANLYBANHANG.Models.MenuForm", null)
                        .WithMany()
                        .HasForeignKey("IdMenuForm")
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATIONS_MENU_FORM_RELATIONS_MENU_FORM");
                });

            modelBuilder.Entity("GroupRelationshipMenuForm", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.MenuForm", null)
                        .WithMany()
                        .HasForeignKey("IdMenuForm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_RELATIONSHIP_MENU_FORM_MENU_FORM");

                    b.HasOne("QUANLYBANHANG.Models.GroupUserRelationshipUser", null)
                        .WithMany()
                        .HasForeignKey("PartyId", "IdGroup")
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_RELATIONSHIP_MENU_FORM_GROUP_USER_RELATIONSHIP_USER");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.Gender", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.GenderType", "GenderType")
                        .WithMany("Gender")
                        .HasForeignKey("GenderTypeId")
                        .IsRequired()
                        .HasConstraintName(" FK__GENDER__GENDER_T__416EA7D8");

                    b.Navigation("GenderType");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.GroupUserRelationshipUser", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.GroupUser", "IdGroupNavigation")
                        .WithMany("GroupUserRelationshipUser")
                        .HasForeignKey("IdGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_USER_RELATIONSHIP_USER_GROUP_USER");

                    b.HasOne("QUANLYBANHANG.Models.Party", "Party")
                        .WithMany("GroupUserRelationshipUser")
                        .HasForeignKey("PartyId")
                        .IsRequired()
                        .HasConstraintName("FK_GROUP_USER_RELATIONSHIP_USER_PARTY");

                    b.Navigation("IdGroupNavigation");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.MenuForm", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.MenuForm", "IdMenuFormParentNavigation")
                        .WithMany("InverseIdMenuFormParentNavigation")
                        .HasForeignKey("IdMenuFormParent")
                        .HasConstraintName("FK_MENU_FORM_MENU_FORM");

                    b.Navigation("IdMenuFormParentNavigation");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.Person", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.Party", "Party")
                        .WithOne("Person")
                        .HasForeignKey("QUANLYBANHANG.Models.Person", "PartyId")
                        .IsRequired()
                        .HasConstraintName("FK_PERSON_PARTY");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbChitietgiohang", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.TbGiohang", "MagiohangNavigation")
                        .WithMany("TbChitietgiohang")
                        .HasForeignKey("Magiohang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GH_GIOHANG");

                    b.HasOne("QUANLYBANHANG.Models.TbSanpham", "MasanphamNavigation")
                        .WithMany("TbChitietgiohang")
                        .HasForeignKey("Masanpham")
                        .IsRequired()
                        .HasConstraintName("FK_GH_SANPHAM");

                    b.Navigation("MagiohangNavigation");

                    b.Navigation("MasanphamNavigation");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbChitiethoadon", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.TbHoadon", "MahoadonNavigation")
                        .WithMany("TbChitiethoadon")
                        .HasForeignKey("Mahoadon")
                        .HasConstraintName("FK_tbCHITIETHOADON_tbHOADON");

                    b.HasOne("QUANLYBANHANG.Models.TbSanpham", "MasanphamNavigation")
                        .WithMany("TbChitiethoadon")
                        .HasForeignKey("Masanpham")
                        .HasConstraintName("FK_tbCHITIETHOADON_tbSANPHAM");

                    b.Navigation("MahoadonNavigation");

                    b.Navigation("MasanphamNavigation");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbHoadon", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.TbKhanhhang", "MakhachhangNavigation")
                        .WithMany("TbHoadon")
                        .HasForeignKey("Makhachhang")
                        .HasConstraintName("FK_tbHOADON_tbKHANHHANG");

                    b.Navigation("MakhachhangNavigation");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbSanpham", b =>
                {
                    b.HasOne("QUANLYBANHANG.Models.TbDanhmuc", "MadanhmucNavigation")
                        .WithMany("TbSanpham")
                        .HasForeignKey("Madanhmuc")
                        .HasConstraintName("FK_tbSANPHAM_tbDANHMUC");

                    b.Navigation("MadanhmucNavigation");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.GenderType", b =>
                {
                    b.Navigation("Gender");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.GroupUser", b =>
                {
                    b.Navigation("GroupUserRelationshipUser");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.MenuForm", b =>
                {
                    b.Navigation("InverseIdMenuFormParentNavigation");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.Party", b =>
                {
                    b.Navigation("GroupUserRelationshipUser");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbDanhmuc", b =>
                {
                    b.Navigation("TbSanpham");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbGiohang", b =>
                {
                    b.Navigation("TbChitietgiohang");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbHoadon", b =>
                {
                    b.Navigation("TbChitiethoadon");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbKhanhhang", b =>
                {
                    b.Navigation("TbHoadon");
                });

            modelBuilder.Entity("QUANLYBANHANG.Models.TbSanpham", b =>
                {
                    b.Navigation("TbChitietgiohang");

                    b.Navigation("TbChitiethoadon");
                });
#pragma warning restore 612, 618
        }
    }
}
